<?php

namespace CervezasBundle\Repository;

/**
 * cervezasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cervezasRepository extends \Doctrine\ORM\EntityRepository
{
}
