cervezas_homepage:
    path:     /
    defaults: { _controller: CervezasBundle:Default:index }
cervezas_cervezaID:
    path:     /TipoCerveza/{id}
    defaults: { _controller: CervezasBundle:cerveza:cerveza }

cervezas_crear:
    path:     /crear/{nombre}/{pais}
    defaults: { _controller: CervezasBundle:cerveza:crearCerveza }

cervezas_create:
    path:     /create
    defaults: { _controller: CervezasBundle:cerveza:crearCervezaFormulario }

cervezas_update:
    path:     /update/{id}
    defaults: { _controller: CervezasBundle:cerveza:actualizarCervezasFormulario }

cervezas_muestraTodo:
    path:     /todo
    defaults: { _controller: CervezasBundle:cerveza:muestraTodo }
